"""add metadata columns to entries

Revision ID: 8f9f77f41ba7
Revises: 
Create Date: 2026-03-23 16:54:00.823978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9f77f41ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('release_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'release_year')
    op.drop_column('entries', 'cover_image')
    op.drop_column('entries', 'external_id')
    # ### end Alembic commands ###
